version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/roboprop/staticfiles
    depends_on:
      - web
    restart: "on-failure"
  web:
    build: .
    volumes:
      - .:/roboprop:rw # map files from the host to the container, useful for development
      - static_volume:/home/app/roboprop/staticfiles
    env_file:
      - .env
    image: roboprop

    expose:
      - 8000
    restart: "on-failure"
  celery:
    build: .
    command: python -m celery -A roboprop worker
    volumes:
      - .:/roboprop:rw
    env_file:
      - .env
    depends_on:
      - redis
    restart: "on-failure"
  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  static_volume:
