version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/roboprop/static
    depends_on:
      - web
    restart: "on-failure"
  web:
    build: . #build the image for the web service from the dockerfile in parent directory
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    npx tailwindcss -i ./static/src/input.css -o ./static/src/output.css &&
                    gunicorn roboprop.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/roboprop:rw # map data and files from parent directory in host to roboprop directory in docker container
      - static_volume:/home/app/roboprop/static
    env_file:
      - .env
    image: roboprop

    expose:
      - 8000
    restart: "on-failure"

volumes:
  static_volume:
