name: "Bump version"

on:
  workflow_call:
    inputs:
      bump_part:
        default: 'minor'
        type: string
        description: "The semver component to bump(major, minor, patch)"
    outputs:
      version:
        description: "The new version determined by this workflow"
        value: "${{ jobs.bump.outputs.version }}"

jobs:
  bump:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.bump_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          # This fetches the entire git history, including tags.
          # Needed in order to bump versions using bump-version
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump-my-version

      - name: Bump version
        id: bump_version
        env:
          GIT_NAME: ${{ github.event.head_commit.author.name }}
          GIT_EMAIL: ${{ github.event.head_commit.author.email }}
          REF: ${{ github.ref }}
        run: |
          git config user.email $GIT_EMAIL
          git config user.name "$GIT_NAME"

          bump-my-version --tag --current-version $(git describe --abbrev=0) ${{ inputs.bump_part }}
          git push --tags
          export VERSION=$(git describe --abbrev=0 | cut -c2- )
          echo "New version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"