name: "CD: Build docker container"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      repository_name:
        required: true
        type: string
      dockerfile:
        default: 'Dockerfile'
        type: string
      build_context:
        default: '.'
        type: string
    secrets:
      access_key_id:
        required: true
      secret_access_key:
        required: true
      aws_region:
        required: true

jobs:
  build_docker:
    runs-on: ubuntu-22.04

    steps:
      - name: Get the source
        uses: actions/checkout@v3

      # Needed for building to ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.access_key_id }}
          aws-secret-access-key: ${{ secrets.secret_access_key}}
          aws-region: ${{ secrets.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build --push --file ${{ inputs.dockerfile }} -t $REGISTRY/${{ inputs.repository_name }}:${{ github.sha }} -t $REGISTRY/${{ inputs.repository_name }}:${{ inputs.version }} ${{ inputs.build_context}}