# Allows you to manually release to the development env
name: Build and deploy development release

on: 
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/callable_ci.yml
  bump_version:
    uses: ./.github/workflows/callable_bump_described_version.yml
    needs: [test]
  build:
    uses: ./.github/workflows/callable_dockerbuild.yml
    with:
      version: ${{needs.bump_version.outputs.version}}
      repository_name: application/${{ github.event.repository.name }}
    secrets:
      access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
    needs: [bump_version]
  publish:
    uses: ./.github/workflows/callable_publish.yml
    with:
      tag: ${{needs.bump_version.outputs.version}}
      environment: development
      repository_name: application/${{ github.event.repository.name }}
    secrets:
      gitops_repo_pat: ${{ secrets.GITOPS_REPO_PAT }}
    needs: [build, bump_version]
