# Ran whenever there is a push/merge to main
name: Build and deploy release

on: 
  push: 
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/callable_ci.yml
  bump_version:
    uses: ./.github/workflows/callable_bump_version.yml
    with:
      bump_part: minor
    needs: [test]
  build:
    uses: ./.github/workflows/callable_dockerbuild.yml
    with:
      version: ${{needs.bump_version.outputs.version}}
      repository_name: application/roboprop
    secrets:
      access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
    needs: [bump_version]
  publish:
    uses: ./.github/workflows/callable_publish.yml
    with:
      tag: ${{needs.bump_version.outputs.version}}
      environment: production
      repository_name: application/roboprop
    secrets:
      gitops_repo_pat: ${{ secrets.GITOPS_REPO_PAT }}
    needs: [build, bump_version]