# Ran whenever there is a push/merge to main
name: Build and deploy release

on: 
  push:

jobs:
  test:
    uses: ./.github/workflows/callable_ci.yml
  bump_version:
    uses: art-e-fact/reusable-gha-workflows/.github/workflows/callable_bump_version.yml@main
    with:
      bump_part: minor
    needs: [test]
  build:
    uses: art-e-fact/reusable-gha-workflows/.github/workflows/callable_dockerbuild.yml@main
    with:
      version: ${{needs.bump_version.outputs.version}}
      repository_name: application/${{ github.event.repository.name }}
    secrets:
      access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
    needs: [bump_version]
  publish:
    uses: art-e-fact/reusable-gha-workflows/.github/workflows/callable_publish.yml@main
    with:
      tag: ${{needs.bump_version.outputs.version}}
      environment: production
      repository_name: application/${{ github.event.repository.name }}
    secrets:
      gitops_repo_pat: ${{ secrets.GITOPS_REPO_PAT }}
    needs: [build, bump_version]